# Generated by Django 5.2 on 2025-04-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmail_app', '0002_alter_emailmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='email_alias',
        ),
        migrations.AddField(
            model_name='emailalias',
            name='mailboxes',
            field=models.ManyToManyField(related_name='accessible_by', to='webmail_app.emailalias'),
        ),
    ]
