# Generated by Django 5.2 on 2025-04-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmail_app', '0003_remove_emailmessage_email_alias_emailalias_mailboxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailalias',
            name='mailboxes',
        ),
        migrations.CreateModel(
            name='AliasMailboxAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessible_mailboxes', to='webmail_app.emailalias')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_mailboxes', to='webmail_app.emailalias')),
            ],
            options={
                'verbose_name': 'Alias Mailbox Access',
                'verbose_name_plural': 'Alias Mailbox Accesses',
                'unique_together': {('owner', 'mailbox')},
            },
        ),
    ]
