# Generated by Django 5.2 on 2025-04-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmail_app', '0004_remove_emailalias_mailboxes_aliasmailboxaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='category',
            field=models.CharField(blank=True, default='Personal', max_length=255),
        ),
        migrations.AlterField(
            model_name='aliasmailboxaccess',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='webmail_app.emailalias'),
        ),
    ]
