# Generated by Django 5.2 on 2025-04-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmail_app', '0005_emailmessage_category_alter_aliasmailboxaccess_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='category',
            new_name='label',
        ),
    ]
