# Generated by Django 5.2 on 2025-04-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmail_app', '0006_rename_category_emailmessage_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
